export * from "./addNewPage";
export * from "./addWidget";
export * from "./deletePage";
export * from "./getAllWidgetDefinitions";
export * from "./getDashboardDefinition";
export * from "./getSettingName";
export * from "./getUserDashboard";
export * from "./renamePage";
export * from "./savePage";
