export * from "./AddNewPage";
export * from "./AddWidget";
export * from "./DeletePage";
export * from "./GetAllWidgetDefinitions";
export * from "./GetDashboardDefinition";
export * from "./GetSettingName";
export * from "./GetUserDashboard";
export * from "./RenamePage";
export * from "./SavePage";
